myproject/base/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path('login/',views.loginPage, name="login"),
    path('logout/',views.logoutPage, name="logout"),
    path('register/',views.registerPage, name="register"),

    path('',views.home,name="home"),
    path('room_page/<int:pk>/',views.room,name="room"),
    path('profile/<str:pk>/',views.userProfile,name="user-profile"),
    
    path('create-room/',views.createRoom,name="create-room"),
    path('update-room/<str:pk>',views.updateRoom,name="update-room"),
    path('delete-room/<str:pk>',views.deleteRoom,name="delete-room"),
    path('delete-message/<str:pk>',views.deleteMessage,name="delete-message"),

    path('update-user/',views.updateUser,name="update-user"),

    path("topics/",views.topicsPage, name="topics"),
    path("activity/",views.activityPage, name="activity"),
]

myproject/myproject/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include('base.urls')),
    path('api/',include('base.api.urls')),
] +static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)


myproject/base/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser

# Create your models here.

class User(AbstractUser):
    name = models.CharField(max_length=200, null=True)
    email = models.EmailField(unique=True,null=True)
    bio = models.TextField(null=True)

    avatar = models.ImageField(null=True,default="avatar.png")

    USERNAME_FIELD = 'email'
    REQUIRED_FIELDS = []


class Topic(models.Model):
    name = models.CharField(max_length=200)

    def __str__(self):
        return self.name

class Room(models.Model):
    host = models.ForeignKey(User, on_delete=models.SET_NULL, null=True)
    topic = models.ForeignKey(Topic, on_delete=models.SET_NULL, null=True) 
    name = models.CharField(max_length=200)
    description = models.TextField(null=True, blank=True)
    participants = models.ManyToManyField(User, related_name='participants',blank=True)
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-updated','-created']

    def __str__(self):
        return self.name
    

class Message(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    room = models.ForeignKey(Room, on_delete=models.CASCADE)
    body = models.TextField()
    updated = models.DateTimeField(auto_now=True)
    created = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-updated','-created']

    def __str__(self):
        return self.body[0:50]

myproject/templates/activity.html
{% extends 'main.html' %}
{% block content %}
<div class=" d-flex justify-content-center align-items-center mt-5 mb-3">
    <div class="col-md-7 col-10">
        <div class="bg-secondary px-3 py-2 d-flex justify-content-between  align-items-center rounded-top ">
            <div>
                <a href="{% url 'home' %}" class="px-3 py-2  " style="font-family: 'Kanit', sans-serif;">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="26" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
                    </svg>
                    RECENT ACTIVITIES
                </a>
            </div>
        </div>
        <div style="background-color:#242424;font-family: 'Kanit', sans-serif; " class="rounded-bottom pb-1 px-3">
            <div style="" class="py-3 ">
                {% for message in room_messages %}
                    <div class="shadow-lg p-3 mb-5 mx-1 mb-3 rounded-3 border-top border-end border-danger-subtle "style="background-color:#5e5d5d;">
                        <div>
                            <small class="" style="font-family: 'Kanit', sans-serif;"><a href="{% url 'user-profile' message.user.id %}" class="fs-5 me-5 mb-3 " >@{{message.user}}</a><br><p class="text-light fs-6">{{message.created|timesince}}</p></small>
                        </div>
                        <div>
                            <a class="text-info" href="{% url 'room' message.room.id %}" style="font-family: 'Kanit', sans-serif;">Replied to "{{message.room}}"</a>
                        </div>
                        <div >
                            <p class="text-dark bg-light   p-3 ps-4 mt-4 rounded-5" style="font-family: 'Kanit', sans-serif;">{{message.body}}</p>
                        </div>
                        <div class=" mt-3 mb-2  text-end" style="font-family: 'Kanit', sans-serif;">
                            {% if request.user == message.user %}
                                <a href="{% url 'delete-message' message.id %}" class="p-2 px-3 bg-danger rounded-5"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
                                    <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
                                  </svg></a>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
        </div>
        </div>
    </div>
</div>
{% endblock  %}

myproject/templates/activity_component.html
{% block content %}
    <div class="d-none d-lg-block">
        <div style="" class="p-2 rounded-bottom rounded-5">
            <h2 class="text-center mt-2 activity romms" style="font-family: 'Borel', cursive;">Recent Activity</h2>
        </div>
        <div style="" class="py-3 ">
                {% for message in room_messages %}
                    <div class="shadow-lg p-3 mb-5 mx-1 mb-3 rounded-3 border-top border-end border-danger-subtle "style="background-color:#5e5d5d;">
                        <div>
                            <img src="{{message.user.avatar.url}}" alt="" style="width: 50px; height: 50px;" class="mb-1 me-2 rounded-5">
                            <small class="" style="font-family: 'Kanit', sans-serif;"><a href="{% url 'user-profile' message.user.id %}" class="fs-5 me-5 mb-3 " >@{{message.user.username}}</a><br><p class="text-light fs-6">{{message.created|timesince}}</p></small>
                        </div>
                        <div>
                            <a class="text-info" href="{% url 'room' message.room.id %}" style="font-family: 'Kanit', sans-serif;">Replied to "{{message.room}}"</a>
                        </div>
                        <div >
                            <p class="text-dark bg-light   p-3 ps-4 mt-4 rounded-5" style="font-family: 'Kanit', sans-serif;">{{message.body}}</p>
                        </div>
                        <div class=" mt-3 mb-2  text-end" style="font-family: 'Kanit', sans-serif;">
                            {% if request.user == message.user %}
                                <a href="{% url 'delete-message' message.id %}" class="p-2 px-3 bg-danger rounded-5">
                                    <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
                                        <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
                                    </svg>
                                </a>
                            {% endif %}
                        </div>
                    </div>
                {% endfor %}
        </div>
    </div>
    {% endblock  %}
        

myproject/templates/delete.html
    {% extends 'main.html' %}
    {% block content %}
    <div class=" d-flex justify-content-center align-items-center mt-5 ">
        <div class="col-md-7 col-10">
            <div class="bg-secondary px-3 py-2 d-flex justify-content-between  align-items-center rounded-top ">
                <div>
                    <a href="{{request.META.HTTP_REFERER}}" class="px-3 py-2  " style="font-family: 'Kanit', sans-serif;">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="26" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
                            <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
                        </svg>
                        CREATE/UPDATE STUDY ROOM
                    </a>
                </div>
            </div>
            <div style="background-color:#242424;font-family: 'Kanit', sans-serif; " class="rounded-bottom">
                <form method="POST" action="">
                    {% csrf_token %}
                    <p class="text-light fs-5 text-center pt-5">Are you sure you want to delete <small class="text-info ">" {{obj}} "</small>  ?</p>
                    <div class="d-flex justify-content-center align-items-center">
                        <input type="submit" class="btn btn-danger my-3 text-center fs-5" value="Confirm" >
                    </div>
                    
                </form>
            </div>
        </div>
    </div>
    {% endblock  %}

myproject/templates/feed_component.html
        
        
        
       <div class="d-flex justify-content-evenly align-items-center mb-4" style="font-family: 'Kanit', sans-serif;">
        <button type="button" class="d-lg-none btn btn-success fs-5"><a href="{% url 'topics' %}">Browse Topics</a></button>
        <button type="button" class="d-lg-none btn btn-success fs-5"><a href="{% url 'activity' %}">Recent Activity</a></button>
       </div>
        <h3 style="font-family: 'Kanit', sans-serif;">Study Room</h3>
        <div class="w-100 d-flex justify-content-between mb-3 align-items-center " style="height: 50px; font-family: 'Kanit', sans-serif;">
            <p class="text-light text-center mt-3">{{rooms.all.count}} rooms available</p>
            <a href="{% url 'create-room'%}" class="p-3  rounded-5 me-3" style="font-family: 'Kanit', sans-serif;">
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-box-arrow-down" viewBox="0 0 16 16">
                    <path fill-rule="evenodd" d="M3.5 10a.5.5 0 0 1-.5-.5v-8a.5.5 0 0 1 .5-.5h9a.5.5 0 0 1 .5.5v8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 0 0 1h2A1.5 1.5 0 0 0 14 9.5v-8A1.5 1.5 0 0 0 12.5 0h-9A1.5 1.5 0 0 0 2 1.5v8A1.5 1.5 0 0 0 3.5 11h2a.5.5 0 0 0 0-1h-2z"/>
                    <path fill-rule="evenodd" d="M7.646 15.854a.5.5 0 0 0 .708 0l3-3a.5.5 0 0 0-.708-.708L8.5 14.293V5.5a.5.5 0 0 0-1 0v8.793l-2.146-2.147a.5.5 0 0 0-.708.708l3 3z"/>
                </svg> Create Room
            </a>
        </div>
        {% for room in rooms %}
            <div id="rooms" class="p-4 m-3 rounded-4 roomm border-top border-end border-text-success-emphasis activity" style="font-family: 'Kanit', sans-serif;">
                <div class="d-flex justify-content-end mb-3">
                    {% if request.user == room.host %}
                        <a href="{% url 'update-room' room.id %}" class="me-3 p-2 px-3 bg-warning rounded-4"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-pencil" viewBox="0 0 16 16">
                            <path d="M12.146.146a.5.5 0 0 1 .708 0l3 3a.5.5 0 0 1 0 .708l-10 10a.5.5 0 0 1-.168.11l-5 2a.5.5 0 0 1-.65-.65l2-5a.5.5 0 0 1 .11-.168l10-10zM11.207 2.5 13.5 4.793 14.793 3.5 12.5 1.207 11.207 2.5zm1.586 3L10.5 3.207 4 9.707V10h.5a.5.5 0 0 1 .5.5v.5h.5a.5.5 0 0 1 .5.5v.5h.293l6.5-6.5zm-9.761 5.175-.106.106-1.528 3.821 3.821-1.528.106-.106A.5.5 0 0 1 5 12.5V12h-.5a.5.5 0 0 1-.5-.5V11h-.5a.5.5 0 0 1-.468-.325z"/>
                          </svg></a>
                        <a href="{% url 'delete-room' room.id %}" class="p-2 px-3 bg-danger rounded-4"><svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-trash-fill" viewBox="0 0 16 16">
                            <path d="M2.5 1a1 1 0 0 0-1 1v1a1 1 0 0 0 1 1H3v9a2 2 0 0 0 2 2h6a2 2 0 0 0 2-2V4h.5a1 1 0 0 0 1-1V2a1 1 0 0 0-1-1H10a1 1 0 0 0-1-1H7a1 1 0 0 0-1 1H2.5zm3 4a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 .5-.5zM8 5a.5.5 0 0 1 .5.5v7a.5.5 0 0 1-1 0v-7A.5.5 0 0 1 8 5zm3 .5v7a.5.5 0 0 1-1 0v-7a.5.5 0 0 1 1 0z"/>
                          </svg></a>
                    {% endif %}
                </div>

                <div class="d-flex justify-content-between align-items-center" >
                    
                    <div>
                        <img src="{{room.host.avatar.url}}" alt="" style="width: 60px; height: 60px;" class="mb-1 me-2 text-light rounded-5">
                        <a href="{% url 'user-profile' room.host.id %}" style="font-family: 'Kanit', sans-serif;" class="fs-5  text-center text-light" >@{{room.host.username}}</a>
                    </div>
                    <span class="text-center text-light fs-6" style="font-family: 'Kanit', sans-serif;">{{room.created|timesince}}</span>
                </div>

                <div class="my-3">
                    <h3><a href="{% url 'room' room.id %}" style="font-family: 'Kanit', sans-serif;">{{room.name}}</a></h3>
                </div>

                <div>
                    <small class="text-light ">{{room.description}}</small><br>
                </div>
                <hr class="border border-danger border-1 opacity-50">
                <div class="d-flex justify-content-between align-items-center">
                    <span class="text-light">
                        <svg xmlns="http://www.w3.org/2000/svg" width="20" height="20" fill="currentColor" class="bi bi-people-fill mb-1 me-1 text-primary" viewBox="0 0 16 16">
                            <path d="M7 14s-1 0-1-1 1-4 5-4 5 3 5 4-1 1-1 1H7Zm4-6a3 3 0 1 0 0-6 3 3 0 0 0 0 6Zm-5.784 6A2.238 2.238 0 0 1 5 13c0-1.355.68-2.75 1.936-3.72A6.325 6.325 0 0 0 5 9c-4 0-5 3-5 4s1 1 1 1h4.216ZM4.5 8a2.5 2.5 0 1 0 0-5 2.5 2.5 0 0 0 0 5Z"/>
                        </svg>
                        Joined
                      {{room.participants.count}}
                    </span>
                    <span class="fs-5 text-light  p-2 rounded-4 border-top border-end border-info" style="background-color: #222729;">{{room.topic.name}}</span>
                </div>
                
            </div>
        {% endfor %}
        

myproject/templates/home.html
{% extends 'main.html' %}
{% block content %}

    <div class="container-fluid">
        <div class="row ">
            <div class="col-lg-3">
               {% include 'topics_component.html' %}
            </div>
            <div class="col-lg-6">
                {% include 'feed_component.html' %}
            </div>
            <div class="col-lg-3">
                {% include 'activity_component.html' %}
            </div>
        </div>
    </div>
{% endblock %}

myproject/templates/login_register.html
{% extends 'main.html' %}
    {% block content %}
    <style>
        .form_group > input{
            width: 100%;
            background-color: black;
            border: 2px solid greay;
            border-radius: 4px;
            color:white;
        }
        .form_group > select{
            width: 100%;
            background-color: black;
            border: 2px solid greay;
            border-radius: 4px;
            color:white;
        }
        .form_group > textarea{
            width: 100%;
            height: 100px;
            overflow-x: hidden; overflow-y: scroll;
            background-color: black;
            border: 2px solid greay;
            border-radius: 4px;
            color:white;
        }
        </style>
    <div class=" d-flex justify-content-center align-items-center mx-5 ">
        <div class="col-md-5 col-12 mb-5">
            {% if page == 'login' %}
            <div class="bg-secondary px-3 py-2 d-flex justify-content-center  align-items-center rounded-top w-100 ">
                <div >
                       <h3 class="px-3 py-2 " style="font-family: 'Kanit', sans-serif;"> LOGIN</h3>
                </div>
            </div>
            
            <div style="background-color:#242424;font-family: 'Kanit', sans-serif; " class="rounded-bottom">
                <p class="text-info fs-5 text-center pt-5">Find your study partner</p>
               
             <div>
            <form method="POST" action="">
                {% csrf_token %}
                <div class="form_group mx-3">
                    <label class=" mb-2 text-light">Email:</label>
                    <input type="text" name="email" >
                </div>
                <div class="form_group mx-3 mt-3">
                    <label class=" mb-2 text-light" >Password:</label>
                    <input type="password" name="password" >
                </div>
                <button class="btn btn-info mt-3 ms-3 " type="submit">
                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-key" viewBox="0 0 16 16">
                        <path d="M0 8a4 4 0 0 1 7.465-2H14a.5.5 0 0 1 .354.146l1.5 1.5a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 1-.708 0L13 9.207l-.646.647a.5.5 0 0 1-.708 0L11 9.207l-.646.647a.5.5 0 0 1-.708 0L9 9.207l-.646.647A.5.5 0 0 1 8 10h-.535A4 4 0 0 1 0 8zm4-3a3 3 0 1 0 2.712 4.285A.5.5 0 0 1 7.163 9h.63l.853-.854a.5.5 0 0 1 .708 0l.646.647.646-.647a.5.5 0 0 1 .708 0l.646.647.646-.647a.5.5 0 0 1 .708 0l.646.647.793-.793-1-1h-6.63a.5.5 0 0 1-.451-.285A3 3 0 0 0 4 5z"/>
                        <path d="M4 8a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
                      </svg>
                      Login
                </button>
                
            </form>

            <p class="text-center text-light">havent signed up yet?</p>
            <div class="d-flex justify-content-center  align-items-center pb-3">
                <a class="text-center text-info w-100" href="{% url 'register' %}">Sign Up</a>
            </div>    
        </div>

        {% else %}
        <div class="bg-secondary px-3 py-2 d-flex justify-content-center  align-items-center rounded-top w-100 ">
            <div >
                   <h3 class="px-3 py-2 " style="font-family: 'Kanit', sans-serif;"> Register</h3>
            </div>
        </div>
        
        <div style="background-color:#242424;font-family: 'Kanit', sans-serif; " class="rounded-bottom">
            <p class="text-info fs-5 text-center pt-5">Find your study partner</p>
           
         <div>
        <div>
            <form method="POST" action="">
                {% csrf_token %}
                {% for field in form %}
                <div class="form_group mx-3 mt-4">
                    <label for="room_name" class="text-light mb-2">{{field.label}}</label>
                    {{field}}
                </div>
                {% endfor %}
                <button class="btn btn-info mt-3 ms-3 " type="submit">
                    <svg xmlns="http://www.w3.org/2000/svg" width="22" height="22" fill="currentColor" class="bi bi-key" viewBox="0 0 16 16">
                        <path d="M0 8a4 4 0 0 1 7.465-2H14a.5.5 0 0 1 .354.146l1.5 1.5a.5.5 0 0 1 0 .708l-1.5 1.5a.5.5 0 0 1-.708 0L13 9.207l-.646.647a.5.5 0 0 1-.708 0L11 9.207l-.646.647a.5.5 0 0 1-.708 0L9 9.207l-.646.647A.5.5 0 0 1 8 10h-.535A4 4 0 0 1 0 8zm4-3a3 3 0 1 0 2.712 4.285A.5.5 0 0 1 7.163 9h.63l.853-.854a.5.5 0 0 1 .708 0l.646.647.646-.647a.5.5 0 0 1 .708 0l.646.647.646-.647a.5.5 0 0 1 .708 0l.646.647.793-.793-1-1h-6.63a.5.5 0 0 1-.451-.285A3 3 0 0 0 4 5z"/>
                        <path d="M4 8a1 1 0 1 1-2 0 1 1 0 0 1 2 0z"/>
                      </svg>
                      Register
                </button>
            </form>

            
            <p class="text-center text-light">havent signed up yet?</p>
            <div class="d-flex justify-content-center  align-items-center pb-3">
                <a class="text-center text-info w-100" href="{% url 'login' %}">Sign Up</a>
            </div> 
        </div>
        {% endif %}
            </div>
        </div>
    </div>
        
    {% endblock  %}

myproject/templates/topics.html
{% extends 'main.html' %}
{% block content %}
<div class=" d-flex justify-content-center align-items-center mt-5 mb-3">
    <div class="col-md-7 col-10">
        <div class="bg-secondary px-3 py-2 d-flex justify-content-between  align-items-center rounded-top ">
            <div>
                <a href="{% url 'home' %}" class="px-3 py-2  " style="font-family: 'Kanit', sans-serif;">
                    <svg xmlns="http://www.w3.org/2000/svg" width="20" height="26" fill="currentColor" class="bi bi-arrow-left" viewBox="0 0 16 16">
                        <path fill-rule="evenodd" d="M15 8a.5.5 0 0 0-.5-.5H2.707l3.147-3.146a.5.5 0 1 0-.708-.708l-4 4a.5.5 0 0 0 0 .708l4 4a.5.5 0 0 0 .708-.708L2.707 8.5H14.5A.5.5 0 0 0 15 8z"/>
                    </svg>
                    BROWSE TOPICS
                </a>
            </div>
        </div>
        <div style="background-color:#242424;font-family: 'Kanit', sans-serif; " class="rounded-bottom pb-1 px-3">
            <div>
                <form action="" method="GET">
                    {% csrf_token %}
                    <input type="search" name="q" id="" class="w-100 bg-info p-2 rounded-3 mt-3 text-light" placeholder="Search Topics ">
                </form>
            </div>
            <ul style=" list-style:none; " class="m-0 p-0" >
                <li class="" style=" list-style-type:none;">
                    <div class="d-flex justify-content-between align-items-center ms-3 pt-2">
                        <a href="{% url 'home' %}" style="font-family: 'Kanit', sans-serif;" class="d-flex justify-content-between ms-3 align-items-center fs-5 mt-3 text-info">ALL</a>
                        <span   class="text-center fs-5 text-light me-3 px-3 py-2 rounded-4">{{topics.count}}</span>
                    </div>
                </li>
                <hr class="text-light">
            </ul>
            {% for topic in topics %}
            <ul style=" list-style:none;" class="m-0 p-0">
                <li  style=" list-style:none;">
                    <div class="d-flex justify-content-between align-items-center ms-3">
                        <a href="{% url 'home' %}?q={{topic.name}}" style="font-family: 'Kanit', sans-serif;" class="d-flex  justify-content-between ms-3  align-items-center fs-5 mt-3 text-info">{{topic.name}}</a>
                        <span id=""  style="font-family: 'Kanit', sans-serif;"  class="text-center fs-5 text-light me-3 px-3 py-2 rounded-4">{{topic.room_set.all.count}}</span>
                    </div>
                    
                </li>
                <hr class="text-light">
            </ul>
            {% endfor %}
        </div>
    </div>
</div>
{% endblock  %}

myproject/templates/topics_component.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
</head>
<body>
    <div class="d-none d-lg-block">
        <h2 class="text-center mb-4 names" style="font-family: 'Borel', cursive;">Browse Topics</h2>
        <div class="shadow-lg  mb-5 pb-3  rounded pt-4 rounded-5 border-2 border-top border-danger" style="background-color:#c9a646;">
            <ul style=" list-style:none; " class="m-0 p-0" >
                <li class="" style=" list-style-type:none;">
                    <div class="d-flex justify-content-md-between align-items-center ms-3">
                        <a href="{% url 'home' %}" style="font-family: 'Kanit', sans-serif;" class="d-flex justify-content-md-between ms-3 align-items-center fs-5 mt-3 text-dark">ALL</a>
                        <span   class="text-center fs-5 text-light me-3 px-3 py-2 rounded-4">{{all_rooms}}</span>
                    </div>
                </li>
            </ul>

            {% for topic in topics %}
            <ul style=" list-style:none;" class="m-0 p-0">
                <li  style=" list-style:none;">
                    <div class="d-flex justify-content-md-between align-items-center ms-3">
                        <a href="{% url 'home' %}?q={{topic.name}}" style="font-family: 'Kanit', sans-serif;" class="d-flex  justify-content-md-between ms-3  align-items-center fs-5 mt-3 text-dark">{{topic.name}}</a>
                        <span id=""  style="font-family: 'Kanit', sans-serif;"  class="text-center fs-5 text-light me-3 px-3 py-2 rounded-4">{{topic.room_set.all.count}}</span>
                    </div>
                    
                </li>
            </ul>
            {% endfor %}
            <a href="{% url 'topics' %}" class="d-flex justify-content-center align-items-center mt-3 btn" >
                <h5 class="text-center text-dark" style="font-family: 'Kanit', sans-serif;">More</h5>
                <svg xmlns="http://www.w3.org/2000/svg" width="16" height="16" fill="currentColor" class="bi bi-caret-down-fill text-dark mb-2" viewBox="0 0 16 16">
                    <path d="M7.247 11.14 2.451 5.658C1.885 5.013 2.345 4 3.204 4h9.592a1 1 0 0 1 .753 1.659l-4.796 5.48a1 1 0 0 1-1.506 0z"/>
                  </svg>
            </a>
        </div>
    </div>
</body>
</html>